default: &default
  adapter: postgresql
  pool:    5
  timeout: 5000

local_credentials: &local_credentials
  login: zool
  password: 

development:
  <<: *default
  <<: *local_credentials
  database: mir_bibnum_development

test:
  <<: *default
  <<: *local_credentials
  database: mir_bibnum_test